version: '3.8'

services:
  app:
    build: .
    volumes: 
      - .:/app/
    ports:
      - 8080:8000
    env_file:
      - .env
    networks:
      - stable_diffusion
    depends_on:
      - db
      - redis
  
  db:
    image: mysql
    restart: always
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - stable_diffusion
  
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - stable_diffusion
  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - stable_diffusion

networks:
  stable_diffusion:
    driver: bridge

volumes:
  