version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    hostname: app
    restart: always
    volumes:
      - .:/app/:rw
    ports:
      - 80:8000
    env_file:
      - .env
    depends_on:
      - redis
      - worker
      - rabbitmq
  
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    hostname: worker
    restart: always
    volumes: 
      - .:/app/:rw
    command: celery -A tasks worker --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
  
  flower:
    build:
      context: .
      dockerfile: worker.Dockerfile
    hostname: flower
    restart: always
    volumes: 
      - .:/app/:rw
    ports:
      - 5555:5555
    command: celery -A tasks flower --port=5555
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
  
  redis:
    image: redis:7.0.5
    hostname: redis
    restart: always
    volumes:
      - .redisdata:/data:rw
    ports:
      - 6379:6379
    env_file:
      - .env
  
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbit
    restart: always
    volumes:
      - .rabbitmqdata/data/:/var/lib/rabbitmq/:rw
      - .rabbitmqdata/log/:/var/log/rabbitmq:rw
    ports:
      - 5672:5672 # AMQP connection
      - 15672:15672 # HTTP connection
      # - 15692 # HTTP prometheus connection
      # - 25672 # Clustering connection
    env_file:
      - .env