services:
  app:
    build: .
    volumes: 
      - .:/app/
    ports:
      - 8080:8000
    env_file:
      - .env
    networks:
      - stable_diffusion
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - stable_diffusion

networks:
  stable_diffusion:
    driver: bridge
